spring.application.name=gameforgehub

# Nombre fijo para la base de datos (evita que cambie al reiniciar)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilita la consola para ver los datos en el navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Esto hace que las tablas se creen solas basado en tu clase User
spring.jpa.hibernate.ddl-auto=update